### ISSUE TITLE
Add a background color to the body of the page

### ISSUE THREAD

**Issue by Vixs101** [Vixs101/hacktoberfest_jalingo#1]
Try adding a background color that will make the page look nice

**Comment by FarhadAliShaikh** [comment]
Intereststing

**Comment by AkshitBhandariCodes** [comment]
hi this side akshit 
assign this to me
i will add the nice background to your page 
i will also help you with the UI and will also make it responsive
@Vixs101

**Comment by sourabhmajoka** [comment]
Hi @Vixs101 , I have successfully resolved the issue and created [Pull Request #2 ]. Please review it when you get a chance. Thank you!

**Comment by AkshitBhandariCodes** [comment]
@Vixs101 brother i have also added a image and changed the baclground
